name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM
        run: sudo apt-get install -y llvm-10

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v

      - name: Covert Swift coverage report to lcov
        run: |
          llvm-cov-10 export -format="lcov" \
          -instr-profile=.build/debug/codecov/default.profdata \
          .build/debug/ClanglerPackageTests.xctest > ./coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .build/debug/codecov/Clangler.json
          fail_ci_if_error: true
